### ISSUE TITLE
Extend sleep beyond 8s

### ISSUE THREAD

**Issue by lbrutti** [rocketscream/Low-Power#102]
Hello,
is there a way to extend sleep period beyond 8s? In my project I need to collect one sample each 15 minutes.

I looked at the code and saw that sleep periods are defined as enum, I couldn't find any numerical value, am I missing something?

thanks,
Lorenzo

**Comment by rocketscream** [comment]
This is as simple as using a `for` loop and count multiple until it reaches the period you needed.
