### ISSUE TITLE
Overwrites memory in my sketch

### ISSUE THREAD

**Issue by lmorris99** [rocketscream/Low-Power#12]
With the library included, and this line: 
  LowPower.powerDown(SLEEP_8S, ADC_OFF, BOD_OFF);
my sketch compiles and starts to run, but displays garbage characters in my debugging messages
 (e.g.,   Serial.print("into fwd run of"); Serial.println(fwd_run_length);   displays as 
"into fwd run of 6ô" )  and other misbehaviors.

if instead I use
   Delay(8000);
then my sketch runs perfectly.

**Comment by crcastle** [comment]
You probably need to add a `Serial.flush();` before sleeping.  The Serial buffer hasn't completely written out before the MCU goes to sleep.
