### ISSUE TITLE
Feature request: add support to Due and Zero

### ISSUE THREAD

**Issue by q2dg** [rocketscream/Low-Power#16]
I don't know if it is very difficult (they are ARM, not AVR) but anyway....thanks!

**Comment by q2dg** [comment]
Hello?...

**Comment by rocketscream** [comment]
Next in my list as having a custom board releasing soon.

**Comment by jassing** [comment]
Hi my friend! Just two days ago I was thinking about you...

On Mon, Nov 9, 2015 at 12:59 AM, rocketscream <notifications@github.com>
wrote:

> Next in my list as having a custom board releasing soon.
>

​how is it coming along?  Hopefully you have been having fun with it.
Hope you are well.
-josh​
