### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by Thijxx** [rocketscream/Low-Power#18]
The example code on your website is not working.. (here: http://www.rocketscream.com/blog/2011/07/04/lightweight-low-power-arduino-library/)
Also, a direct link to an installable ZIP file would be nice.
Also, any directions on using this would be nice.
Also, would be nice to have the example code right here on GitHub.  

'ADC_CONTROL_OFF' was not declared in this scope`

**Comment by rocketscream** [comment]
@Thijxx I wrote that article quite a while ago while the library was on it's initial release. There were some naming convention changes along the way. The library has examples bundled together (of course with the correct constants). I will edit the article on top of that. Thank you.
