### ISSUE TITLE
Feature Request: ESP8266 Support

### ISSUE THREAD

**Issue by TheY3TI** [rocketscream/Low-Power#25]
Hi!

First of all, this library is great! It greatly reduces power consumption without any real effort.
That's why I'm interested in something similar for the now very popular ESP8266 which is seriously power hungry. I think you'd make a lot of people very happy.

Thanks for considering and keep up the good work!
Brent

**Comment by rocketscream** [comment]
I believe it has been implement on the ESP8266 core already? Take a look [here](https://github.com/esp8266/Arduino/blob/master/doc/libraries.md#esp-specific-apis). The ESP8266 has more consideration before going into sleep as it has a full stack implementation of WiFi running on it.

**Comment by TheY3TI** [comment]
Indeed it has been, thank you very much for the quick answer!
