### ISSUE TITLE
'SLEEP_MODE_EXT_STANDBY'

### ISSUE THREAD

**Issue by Tiebolt** [rocketscream/Low-Power#29]
C:\users\xxxxx.platformio\lib\Low_Power_ID38\LowPower.cpp:985:17: error: 'SLEEP_MODE_EXT_STANDBY' was not declared in this scope`

C:\users\xxxxx.platformio\lib\Low_Power_ID38\LowPower.cpp:985:3: note: in expansion of macro 'lowPowerBodOn'
lowPowerBodOn(SLEEP_MODE_EXT_STANDBY);

Running on:
platform = atmelavr
board = pro16MHzatmega168
framework = arduino

**Comment by rocketscream** [comment]
Will be patched for the next revision, for now please refer to the solution here #14 
The AVR distribution didn't declare the extended sleep mode.
