### ISSUE TITLE
compatible with the mini ultra pro?

### ISSUE THREAD

**Issue by mema0341** [rocketscream/Low-Power#38]
I saw that this library was compatible for the mini ultra pro board, but it seems that they were written for the Arduino ATmega boards and the mini ultra pro board is compatible with the Arduino Zero boards?

**Comment by rocketscream** [comment]
Only the standby mode is currently supported. I would suggest using the [RTCZero library](https://github.com/arduino-libraries/RTCZero) instead as it also has a standby function call similar to the one on this library. Take a look at the example on our [documentation](http://www.rocketscream.com/blog/docs-item/using-rtc-in-low-power-mode-on-mini-ultra-pro/).
