### ISSUE TITLE
TX Led

### ISSUE THREAD

**Issue by marwin1991** [rocketscream/Low-Power#48]
I am wondering why when I use LowPower.powerDown(SLEEP_1S, ADC_OFF, BOD_OFF);  
on board TX Led is turn on and exiting this function is turn off? I use Arduino Nano 3.0 clone.

**Comment by rocketscream** [comment]
You would need to take care of pins state on the MCU as it is application specific. On Arduino Nano, that LED are connected to the USB chip which is not control by the MCU.

**Comment by NeoLegends** [comment]
For me wrapping the .powerDown-calls with `Serial.end()` and `Serial.begin(9600)` did the trick and the LED switched off.
