### ISSUE TITLE
Never comeback from powerDown on Adafruit Feather 32u4 ( LoRa board)

### ISSUE THREAD

**Issue by vtomanov** [rocketscream/Low-Power#49]
Just executing : 

LowPower.powerDown(SLEEP_500MS, ADC_OFF, BOD_OFF);

start sleeping and never come back out of it

**Comment by drmpf** [comment]
As an alternative to struggling with low power sleep you could try my FET Power Off circuit which removes the battery once the operation has been completed.
[Long Life On/Off Remote WiFi, Bluetooth, BLE, Radio/LoRa or SMS](https://www.forward.com.au/pfod/HomeAutomation/WiFi_OnOff/index.html)

**Comment by rocketscream** [comment]
Please take a look at my explanation [here](http://www.rocketscream.com/blog/forums/topic/adafruit-feather-32u4-fona-wakeup-no-serial-print/).
