### ISSUE TITLE
Current consumption on SAMD board?

### ISSUE THREAD

**Issue by brolly759** [rocketscream/Low-Power#55]
Has anyone done the power calculations on the ATSAMD21G18A processor for each of the examples? Can we hit 4.4uA as it says in the datasheet? How much current is drawn when using external interrupt, using WDT timer, etc? 

I wish the community adopted the SAML21 series which is geared towards lower sleep current.

Thanks!

**Comment by rocketscream** [comment]
Yes, you can but it's not as simple as putting the MCU into the sleep mode (standby mode). The pins state must be carefully taken care of together with the USB port handling. Please take a look at the example [here](https://github.com/rocketscream/MiniUltraPro/blob/master/ttn-otaa-sleep.ino).
