### ISSUE TITLE
Interupts FALLING, RISING CHANGE not working when in sleep

### ISSUE THREAD

**Issue by milesfrankland** [rocketscream/Low-Power#58]
Hi,
I had my SAMD21 working whilst awake using the FALLING, RISING CHANGE interrupt mode.
When the device went to sleep however, the interrupt would not work and wake up the device.
I added this to my setup routine:
```
	SYSCTRL->VREG.bit.RUNSTDBY = 1;
	SYSCTRL->DFLLCTRL.bit.RUNSTDBY = 1;
```
And it all works now.
Not sure if you can implement this into Low-Power?
Thanks

**Comment by rocketscream** [comment]
This is a known issue that due to the clock used to drive the peripheral being off during sleep. This should be solved within the SAMD21 core itself to make things cleaner.
