### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by jgartner1** [rocketscream/Low-Power#61]
Hey. I am using a neewly bought arduino micro, and I tried the testexample where you can suspend it for 8 seconds. I imported the libary included the headerfile and tried to execute it and to print out a text every 8 seconds. But after the first iteration it just stops. Any idea what I could have done wrong? Do i need to import more libaries? Or is a serial connection just not possible right after suspension?

**Comment by sysshad** [comment]
You might need to implement something that waits for the Serial data to be written out before it enters the 2nd sleep cycle. That is because the Serial has a buffer which takes time to output, and in the meanwhile if you try to enter 2nd sleep it doesnt have enough time.

**Comment by sysshad** [comment]
I think its the Serial.flush(); you need to call if i remember correctly
