### ISSUE TITLE
Support Atmega 4809

### ISSUE THREAD

**Issue by moebius911** [rocketscream/Low-Power#79]
Hello

is a support for atmega 4809 (arduino wifi rev2) is in progress? I started to look at the code but unfortunately my knowledge is weak to contribute to its development.
thank you in advance

**Comment by rocketscream** [comment]
Will do once we have a test board up. A bit busy with other things at the moment.

**Comment by nimasaj** [comment]
It would be great help if you support this MCU as well.

**Comment by AndersDenmark** [comment]
Yes support for this MCU would be really nice. working on a small break out board for this nice and small processor, will use Curiosity Nano Kit for the UPDI upload, and also serial monitoring. Until i can get Arduino Uno or Atmel Ice to work on the Arduino IDE. Please let me know if there is something i can do to help….

**Comment by papu256** [comment]
Yeah it would be nice.  Thanks!!!

**Comment by nulaft** [comment]
I would also be interested in this for the Arduino Nano Every!

**Comment by rocketscream** [comment]
Already tested this on ATmega4808 physically. This will be implemented on a new library and they are quite different. Watchdog timer no longer behaves as it used to on the older ATmega (now solely to reset the MCU) and a real time counter (RTC) is used instead. Will update here once release, should be soon.

**Comment by kwinter24** [comment]
> Already tested this on ATmega4808 physically. This will be implemented on a new library and they are quite different. Watchdog timer no longer behaves as it used to on the older ATmega (now solely to reset the MCU) and a real time counter (RTC) is used instead. Will update here once release, should be soon.

Any update on this?  Arduino nano is screaming for a good low power library.  Thanks in advance!

**Comment by thomasjungblut** [comment]
Also hitting the issue right now with the nano every. @rocketscream anyway I can help out to get this to work?

**Comment by rocketscream** [comment]
I'm currently already using it on some custom works. Will update soon, just some tiny bugs needs to be iron out.

**Comment by rocketscream** [comment]
[LowPowerAVRZero](https://github.com/rocketscream/RocketScream_LowPowerAVRZero) library for megaAVR 0-series has been released. Can be used with [RTCAVRZero](https://github.com/rocketscream/RocketScream_RTCAVRZero) for real time counter functionality which replaces the watchdog timer based sleep timer.
