### ISSUE TITLE
Adding Rising/Falling  interrupt support

### ISSUE THREAD

**Issue by maxholgasson** [rocketscream/Low-Power#82]
Hi,
i need to wake up my Mini Ultra Pro V3 on LOW and on RISING. LOW i got running with this library. but Falling or Rising didn't work. Can this be fixed somehow?

**Comment by CaptChilko** [comment]
Seconded, this would be a great addition

**Comment by rocketscream** [comment]
This is now supported on the [Arduino Low Power Library](https://github.com/arduino-libraries/ArduinoLowPower) supporting the SAMD21 core. I will remove the SAMD21 support on this library soon.

**Comment by maxholgasson** [comment]
Thanks! Really?? The SAMD21 is such a great expansion when more power and space is needed..and in almost every battery powered operation you need the low power library
