### ISSUE TITLE
Feature Request: Add Support for ATMega1284P

### ISSUE THREAD

**Issue by WickedDevice** [rocketscream/Low-Power#9]
ATMega1284P is not currently supported. It's quite similar to the ATmega328P though looking at the respective datasheets section 10.1 Sleep Modes. Happy to help test using my WildFire ATmega128P-based platform if you can give me some direction. /cc @vicatcu

**Comment by urs8000** [comment]
two years ago, this request was issued  -  pleas go for it. thanks.

**Comment by vicatcu** [comment]
@urs8000 @rocketscream it looks like there's been activity on this repo within the last few months, couldn't say why nobody ever responded to my original issue being posted, my offer to help still stands, but I also still need som minimal guidance on how to proceed.

**Comment by rocketscream** [comment]
Hi guys,

Thank you for the suggestions. Wanted to add ATMega1284P but did not have the chance to actually test on a real hardware based on ATMega1284P/644P. If time permits, I will spin a simple board to test. No point releasing codes that is not tested on a real hardware.

**Comment by vicatcu** [comment]
@rocketscream I'm pretty sure I could strip down an old WildFire to make it be just an ATmega1284P with supporting passives, crystal, and an ICSP connector and send it to you if that helps. Could also leave leave the FTDI circuitry in place. Assuming you are only doing delta current analysis, either of those approaches would probably work, but if you're going for bare metal absolute current measurements with sense resistors and amplifiers and such I can see the merits of rolling your own board to ease that process. Anyway, like I said, willing to support and provide hardware if it helps.

**Comment by rocketscream** [comment]
@vicatcu Just only grab some ATMega1284P in DIP form from Element-14 with 8 & 16 MHz crystals. Will test them and update the library.

**Comment by gpshead** [comment]
FYI - The fork of this library in https://github.com/lowpowerlab/lowpower simply added 1284P to the 328P ifdefs.

**Comment by rocketscream** [comment]
Support for ATMega1284P has been added since V1.70.
