### ISSUE TITLE
Powering down arduino indefinetly

### ISSUE THREAD

**Issue by batata004** [rocketscream/Low-Power#96]
Hi,

I have a code that when it reaches a conditional, I want arduino to go to sleep permanently, saving as much battery as possible. I am using this:

LowPower.powerDown(SLEEP_8S, ADC_OFF, BOD_OFF);

However it sleeps for only 8S. Is there a way I can make it sleep indefinitly until I power off/power on it again?

**Comment by nimasaj** [comment]
Why not using `LowPower.powerDown(SLEEP_FOREVER, ADC_OFF, BOD_OFF);` ?

**Comment by batata004** [comment]
SLEEP_FOREVER does it exist? great!
