### ISSUE TITLE
Define the sleep time.

### ISSUE THREAD

**Issue by alessandrolecce** [rocketscream/Low-Power#98]
Is it possible to define sleep time? 
I need to sleep the Arduino for 5 minutes. How can I implement it in LowPower.idle() ?

**Comment by Adrian363** [comment]
Hi, 
I want to make the same thing as you. Have you found a solution to increase sleeping time?

**Comment by alessandrolecce** [comment]
Not, yet, I will work on it by the end of this month

Inviato da Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by ziplock9000** [comment]
This is exactly what I was coming to request too :)

**Comment by zvoniimiir** [comment]
Have you tried powerDown? sleepCounter represents 8s periods (due to SLEEP_8S). So 5 minutes would be sleepCounter = 38 

`for (int sleepCounter = 38; sleepCounter > 0; sleepCounter--) 
  {
    LowPower.powerDown(SLEEP_8S, ADC_OFF, BOD_OFF);
  }`

**Comment by ziplock9000** [comment]
> Have you tried powerDown? sleepCounter represents 8s periods (due to SLEEP_8S). So 5 minutes would be sleepCounter = 38
> 
> `for (int sleepCounter = 38; sleepCounter > 0; sleepCounter--) { LowPower.powerDown(SLEEP_8S, ADC_OFF, BOD_OFF); }`

That still means it's wakes up every multiple of 8 seconds. While this would be sufficient for most use cases, but it does not have a single defined sleep time with no wakes like the title mentions.

**Comment by rocketscream** [comment]
The timer is based on the watchdog timer which has discrete period that cannot be changed. Using the `for` loop is the only way here without any external RTC IC or upgrade to the newer [megaAVR 0-series MCU that has real time counter](https://github.com/rocketscream/RocketScream_RTCAVRZero).
